### ISSUE TITLE
Optimiser utility evaluator crashes permanently if recieves an invalid answer from SAL

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/optimiser-utility-evaluator#17]
On PROD (r1 branch), if an edge device has been register without "price", "provider", "cpu", "gpu" or "ram",  utility evaluator crashes with:

![image](https://github.com/user-attachments/assets/b7d6eb5c-b338-402a-a45b-a5aeb86ef692)

After the crash, utility evaluator will no longer respond to any other request.

**Comment by martaroz** [comment]
@robert-sanfeliu looks like an easy fix, I can do it on Wednesday

**Comment by robert-sanfeliu** [comment]
Also, if possible, be forgiving about possible null values for cpu, gpu, fpga, ram, etc... assume safe values (e.g: 0)
